# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Nvim without any statusbar, and savequit when pressing enter
c.editor.command = [
    "kitty",
    "--title", "qutebrowser-floating-url-edit",
    "nvim",
    "-n",
    "+set laststatus=0 noshowmode",
    "+nnoremap <CR> :wq<CR>",
    "+inoremap <CR> <Esc>:wq<CR>",
    "+vnoremap <CR> <Esc>:wq<CR>",
    "{file}"
]
c.auto_save.session = True

config.bind("eu", "edit-url")
